In [ ]:
import numpy as np

In [ ]:
docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquilab zindabad']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

17

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [2, 2, 10],
 [3, 11, 3, 1],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post')
sequences

array([[ 9,  1,  0,  0],
       [ 1,  1,  0,  0],
       [ 2,  2, 10,  0],
       [ 3, 11,  3,  1],
       [12, 13,  4,  5],
       [ 6,  6,  0,  0],
       [ 7,  7,  0,  0],
       [ 8,  8,  0,  0],
       [14, 15,  4,  5],
       [16, 17,  0,  0]], dtype=int32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(17, output_dim=2, input_length=5))

In [ ]:
model.compile('adam', 'accuracy')

In [ ]:
sequences = np.clip(sequences, 0, 16)

pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
[[[-0.00136174  0.0439494 ]
  [ 0.02158644 -0.01779016]
  [ 0.02733142 -0.03885023]
  [ 0.02733142 -0.03885023]]

 [[ 0.02158644 -0.01779016]
  [ 0.02158644 -0.01779016]
  [ 0.02733142 -0.03885023]
  [ 0.02733142 -0.03885023]]

 [[ 0.02139003 -0.01216776]
  [ 0.02139003 -0.01216776]
  [-0.00932165  0.02031353]
  [ 0.02733142 -0.03885023]]

 [[-0.04584002 -0.01599006]
  [-0.04085668 -0.03662983]
  [-0.04584002 -0.01599006]
  [ 0.02158644 -0.01779016]]

 [[-0.01917003  0.01210002]
  [ 0.00366277 -0.03103024]
  [-0.02015094 -0.04748013]
  [ 0.02560531 -0.00979672]]

 [[ 0.03503902 -0.03466899]
  [ 0.03503902 -0.03466899]
  [ 0.02733142 -0.03885023]
  [ 0.02733142 -0.03885023]]

 [[ 0.03698729  0.01559149]
  [ 0.03698729  0.01559149]
  [ 0.02733142 -0.03885023]
  [ 0.02733142 -0.03885023]]

 [[-0.0349112   0.01843239]
  [-0.0349112   0.01843239]
  [ 0.02733142 -0.03885023]
  [ 0.02733142 -0.03885023]]

 [[ 0.00633713  0.01919831]
  [ 0.0213005  -0.043

In [ ]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN, Embedding, Flatten

In [ ]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

In [ ]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - acc: 0.5204 - loss: 0.6901 - val_acc: 0.6991 - val_loss: 0.5793
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - acc: 0.7883 - loss: 0.4591 - val_acc: 0.8115 - val_loss: 0.4145
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 16ms/step - acc: 0.8642 - loss: 0.3270 - val_acc: 0.8047 - val_loss: 0.4283
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - acc: 0.9025 - loss: 0.2515 - val_acc: 0.7887 - val_loss: 0.4738
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 17ms/step - acc: 0.9209 - loss: 0.2168 - val_acc: 0.7888 - val_loss: 0.5647


In [ ]:
# Get the word index used by the IMDB dataset
word_index = imdb.get_word_index()

# Adjust indices (Keras reserves 0-3)
word_index = {k: (v + 3) for k, v in word_index.items()}
word_index["<PAD>"] = 0
word_index["<START>"] = 1
word_index["<UNK>"] = 2
word_index["<UNUSED>"] = 3

In [ ]:
def simple_encode(text):
    words = text.lower().split()
    encoded = [1] # Start token
    for word in words:
        encoded.append(word_index.get(word, 2)) # Unknown if not found
    return pad_sequences([encoded], maxlen=50, padding='post')

In [ ]:
# Your custom sentence
text = "the movie was bad"

# Encode and predict
encoded = simple_encode(text)
pred = model.predict(encoded)

print("Sentiment score:", pred[0][0])
print("Prediction:", "Positive " if pred[0][0] >= 0.5 else "Negative")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step
Sentiment score: 0.021202022
Prediction: Negative
